UDP_IP_LOCALHOST = "127.0.0.1"
SIZE_PKG = 1000

# Usar localhost para Windows
UDP_IP = "127.0.0.1"
UDP_PORT = 5005
TUPLA_DIR = (UDP_IP, UDP_PORT)

UDP_CLIENT_IP = "127.0.0.1"
UDP_CLIENT_PORT = 5006
TUPLA_DIR_CLIENT = (UDP_CLIENT_IP, UDP_CLIENT_PORT)
TUPLA_DIR_ENVIO = (UDP_IP, UDP_PORT)

DOWNLOAD = "D"
UPLOAD = "U"

ACK_TIMEOUT_GBN = 0.05
ACK_TIMEOUT_SW = 0.05

STOP_AND_WAIT = "SW"
GO_BACK_N = "GBN"

PROTOCOLO = STOP_AND_WAIT
WINDOW_SIZE_GBN = 10
WINDOW_SIZE_SW = 1
