UDP_IP_LOCALHOST = "127.0.0.1"
SIZE_PKG = 25

UDP_IP = '10.0.0.1'
UDP_PORT = 5005
TUPLA_DIR = (UDP_IP, UDP_PORT)

UDP_CLIENT_IP = '10.0.0.2'
UDP_CLIENT_PORT = 5006
TUPLA_DIR_CLIENT = (UDP_CLIENT_IP, UDP_CLIENT_PORT)
TUPLA_DIR_ENVIO = (UDP_IP, UDP_PORT)

ACK = 'ACK'
END = 'END'
DOWNLOAD = 'D'
UPLOAD = 'U'