#!/usr/bin/env python3
"""
Script de download para transferencia de archivos UDP
"""
import sys
import os

# Agregar el directorio src al path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))

from src.lib.client.client import main

if __name__ == "__main__":
    main()
