#!/usr/bin/env python3
"""
Script para iniciar el servidor de transferencia de archivos UDP
"""
import sys
import os

# Agregar el directorio src al path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))

from src.lib.server.server import main

if __name__ == "__main__":
    main()
